function(system_target)
    set(targets ${TLLS_UNPARSED_ARGUMENTS})
    foreach(target ${targets})
        get_target_property(sys_inc_dirs ${target} INTERFACE_SYSTEM_INCLUDE_DIRECTORIES)
        get_target_property(inc_dirs ${target} INTERFACE_INCLUDE_DIRECTORIES)
        list(APPEND sys_inc_dirs ${inc_dirs})
        set_target_properties(${target} PROPERTIES INTERFACE_SYSTEM_INCLUDE_DIRECTORIES ${sys_inc_dirs})
        set_target_properties(${target} PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "")
    endforeach()
endfunction(system_target)